nginx:
  hostname: nginx
  build: ./_nginx/
  links:
    - aipo:aipo
    #- owncloud:owncloud
    - blog:blog
    #- creativeclub:creativeclub
  ports:
    - 80:80
  restart: always
  privileged: true
  volumes:
    - ./_nginx/volumes/docker.conf.d:/usr/local/nginx/conf.docker.d

aipo:
  hostname: aipo
  build: ./aipo/
  privileged: true
  volumes:
    - ./volumes/aipo/backup:/opt/aipo/backup

#owncloud:
#  hostname: owncloud
#  image: jchaney/owncloud

blog:
  hostname: blog
  build: ./dcww/
  privileged: true
  environment:
    WP_URL: blog.hachi.sraft.org
    WP_TITLE: Hachioji_Blog
    WP_USER: root
    WP_PASSWORD: change_me_first
    WP_EMAIL: example@example.com
    WP_VERSION: 4.2.1
    WP_LOCALE: ja
    WP_ALLOW_MULTISITE: 1
  volumes:
    - ./volumes/blog:/var/www/html
    - ./dcww/volumes/nginx_conf.d:/etc/nginx/conf.d
    - ./volumes/wordpress-scripts:/opt/wordpress
